# SPDX-License-Identifier: Apache-2.0
name: "050: [USER] Memory Profile Ctrl"
on:
  workflow_dispatch:
    inputs:
      nlg-accounts: #'-R -c 32 -a 100000000 -T 1000 -n 100000 -S hot -p 50 -tt 1m
        required: true
        default: "100000"
        description: "Number of Accounts and NFT tokens"
        type: choice
        options:
          - "100"
          - "1000"
      nlg-time: #'-R -c 32 -a 100000000 -T 1000 -n 100000 -S hot -p 50 -tt 1m
        required: true
        default: "3"
        description: "Test execution time options"
        type: choice
        options:
          - "1"
          - "20"
          - "120"
      add-app-props:
        required: false
        default: ""
        type: string
        description: 'Add props to application.properties, e.g. "blockStream.streamMode=RECORDS". Newline is "\n"'
      add-settings:
        required: false
        default: ""
        type: string
        description: 'Add props to settings.txt, e.g. "state.saveStatePeriod, 300". Newline is "\n"'

defaults:
  run:
    shell: bash

permissions:
  contents: write
  id-token: write
  actions: write
  statuses: write

env:
  GS_ROOT_DIR: gs://performance-engineering-reports/ephemeral/test_runs
  GS_ROOT_HTTPS: https://perf.analytics.eng.hashgraph.io/ephemeral/test_runs

jobs:
  run-single-node-tests:
    name: Single node tests
    runs-on: hl-cn-mem-profiler-lin
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
        with:
          workload_identity_provider: "projects/716789254648/locations/global/workloadIdentityPools/perf-eng-reports-pool/providers/gh-provider"
          service_account: "gh-perf-report-writer@perf-engineering-reports.iam.gserviceaccount.com"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2

      - name: Checkout BlockNode scripts
        if: false
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: hiero-ledger/hiero-block-node
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          ref: master
          path: "./hiero-block-node"

      - name: Checkout BlockNode scripts
        run: |
          git clone https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/hiero-ledger/hiero-block-node.git hiero-block-node

      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: "v3.12.3" # helm version

      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.39.2

      - name: Install KubeCtl
        uses: step-security/setup-kubectl@2edbf6aff97d814e9dc52827498ac51fe972e6d0 # v4.0.0
        with:
          version: v1.33.0

      # Set up kind; needed for configuring the solo environment
      - name: Setup Kind
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          install_only: true
          node_image: kindest/node:v1.31.4@sha256:2cb39f7295fe7eafee0842b1052a599a4fb0f8bcf3f83d96c7f4864c357c6c30
          version: v0.26.0
          kubectl_version: v1.31.4
          verbosity: 3
          wait: 120s

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.18.0

      - name: Install Solo
        run: |
          npm install -g "@hiero-ledger/solo@${{ inputs.solo-version || 'latest' }}"

          # verify the installation
          solo --version

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 25

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io net-tools iputils-ping node-typescript snapd

          #YQ
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install -y yq zip unzip
          sudo apt install -y x11-common x11-session-utils x11-utils x11-xserver-utils

      - name: Install Memory Analyzer
        run: |
          gcloud --no-user-output-enabled storage cp --recursive gs://performance-engineering-reports/permanent/MemoryAnalyzer-1.16.1.20250109-linux.gtk.x86_64.zip ${HOME}/MemoryAnalyzer-1.16.1.20250109-linux.gtk.x86_64.zip
          unzip -q -d ${HOME} ${HOME}/MemoryAnalyzer-1.16.1.20250109-linux.gtk.x86_64.zip
          ls ${HOME}/mat

      - name: Deploy K8S pod
        run: |
          ls -l
          cd hiero-block-node/tools-and-tests/scripts/solo-e2e-test
          task up

      - name: Start Memory capturing
        run: |
          cd "${{ github.workspace }}"/
          cat <<'EOF' > heapInfoByPod.sh
          set +e
          set +x
          for i in `kubectl -n solo-network get pods | awk '{print $1}' | grep -v NAME`;\
          do \
            kubectl -n solo-network  exec ${i}  -- \
            bash -c "jpid=\$(ps -aef | grep -w java | grep -v grep | awk '{print \$2}'); \
              if [ \"\$jpid\" != \"\" ]; then echo \"pod $i:\"; \
                jcmd \$jpid GC.heap_info; echo \"\"; \
                jmap -dump:live,format=b,file=/tmp/test.hprof \$jpid; fi"; \
          done 2>/dev/null
          EOF
          nohup bash -c 'sleep 500; sh heapInfoByPod.sh' > heapInfoByPod.log 2>&1 &

      - name: Run NLG test
        run: |
          cd hiero-block-node/tools-and-tests/scripts/solo-e2e-test
          task load:up NLG_TEST_TYPE=CryptoTransferLoadTest NLG_ARGS="-c 1 -a 1000 -tt 600s" NLG_MAX_TPS=100

      - name: Stop NLG test
        run: |
          cd hiero-block-node/tools-and-tests/scripts/solo-e2e-test
          task load:down

      - name: Report Kubernetes resources
        run: |
          kubectl -n solo-network describe nodes

      - name: Create report dir
        shell: bash
        run: |
          mkdir "${{ github.workspace }}"/report

      - name: Java heap info
        run: |
          set +e
          set +x
          cd "${{ github.workspace }}"/
          cat heapInfoByPod.log

      - name: Analyze Java heaps
        run: |
          set +e
          set +x
          cd "${{ github.workspace }}"/
          #process hprof-s
          for i in `kubectl -n solo-network get pods | awk '{print $1}' | grep -v NAME`;\
          do \
            kubectl -n solo-network cp ${i}:/tmp/test.hprof $i.hprof 2>/dev/null
            if [ -f $i.hprof ]
            then
              mkdir $i
              cd $i
              mv ../$i.hprof ./$i.hprof
              bash ${HOME}/mat/ParseHeapDump.sh ./$i.hprof org.eclipse.mat.api:overview
              unzip -d "${{ github.workspace }}"/report/$i ${i}_System_Overview.zip
              cd "${{ github.workspace }}"/
            fi
          done

      - name: Publish logs
        run: |
          gcloud --no-user-output-enabled storage cp --recursive "${{ github.workspace }}"/report "${{ env.GS_ROOT_DIR }}/MemoryProfile_${{ github.run_number }}"/report
          echo Done: solo deploy logs  in "${{ env.GS_ROOT_HTTPS }}/MemoryProfile_${{ github.run_number }}"/report
