# SPDX-License-Identifier: Apache-2.0
name: "[CITR] XTS Dry Run"
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: "The commit sha, tag, or branch to check out"
      branch_name:
        required: false
        description: "The branch name, for JRS Panel output"
      enable-timing-sensitive-test-suite:
        type: boolean
        description: "Run Timing Sensitive Test Suite"
        default: true
      enable-hammer-test-suite:
        type: boolean
        description: "Run Hammer Test Suite"
        default: true
      enable-hapi-test-suite:
        type: boolean
        description: "Run HAPI Test Suite"
        default: true
      enable-otter-test-suite:
        type: boolean
        description: "Run Otter Test Suite"
        default: true
      enable-chaos-otter-test-suite:
        type: boolean
        description: "Run Chaos Otter Test Suite"
        default: true
      enable-hedera-node-jrs-panel:
        required: true
        type: boolean
        default: true
        description: "Run Hedera Node JRS Panel"
      enable-sdk-tck-regression-panel:
        required: true
        type: boolean
        default: true
        description: "Run SDK TCK Regression Panel"
      enable-mirror-node-regression-panel:
        required: true
        type: boolean
        default: true
        description: "Run Mirror Node Regression Panel"
      enable-rpc-relay-regression-panel:
        required: true
        type: boolean
        default: true
        description: "Run JSON-RPC Relay Regression Panel"
      enable-block-node-regression-panel:
        required: true
        type: boolean
        default: true
        description: "Run Block Node Regression Panel"
      execute-state-validator-build:
        required: true
        type: boolean
        default: true
        description: "Execute the State Validator Uber JAR build job"

permissions:
  id-token: write
  actions: write
  issues: write
  pull-requests: write
  statuses: write
  checks: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  parameters:
    name: Workflow Parameters
    runs-on: hl-cn-default-lin-sm
    outputs:
      solo-version: ${{ steps.params.outputs.solo-version }}
      helm-release-name: ${{ steps.params.outputs.helm-release-name }}
      solo-ge-0440: ${{ steps.params.outputs.solo-ge-0440 }}
    steps:
      - name: Initialize GitHub Job
        uses: pandaswhocode/initialize-github-job@bfe0b1633012cee3033c757c7095d49c360e23a6 # v1.0.1

      - name: Print Params
        id: params
        run: |
          SOLO_GE_0440=$([[ "$(printf '%s\n' "${{vars.ADHOC_XTS_SOLO_VERSION}}" "v0.44.0" | sort -V | head -n1)" == "v0.44.0" ]] && echo "true" || echo "false")
          HELM_NAME="mirror"
          if [[ "${SOLO_GE_0440}" == "true" ]]; then
            HELM_NAME="mirror-1"
          fi
          echo "Commit SHA: ${{ inputs.ref }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Branch Name: ${{ inputs.branch_name }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable Timing Sensitive Test Suite: ${{ inputs.enable-timing-sensitive-test-suite }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable Hammer Test Suite: ${{ inputs.enable-hammer-test-suite }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable HAPI Test Suite: ${{ inputs.enable-hapi-test-suite }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable Otter Test Suite: ${{ inputs.enable-otter-test-suite }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable Chaos Otter Test Suite: ${{ inputs.enable-chaos-otter-test-suite }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable Hedera Node JRS Panel: ${{ inputs.enable-hedera-node-jrs-panel }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable SDK TCK Regression Panel: ${{ inputs.enable-sdk-tck-regression-panel }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable Mirror Node Regression Panel: ${{ inputs.enable-mirror-node-regression-panel }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable JSON-RPC Relay Regression Panel: ${{ inputs.enable-rpc-relay-regression-panel }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Enable Block Node Regression Panel: ${{ inputs.enable-block-node-regression-panel }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Solo Version: ${{ vars.ADHOC_XTS_SOLO_VERSION }}" | tee -a "${GITHUB_STEP_SUMMARY}"
          echo "Helm Release Name: ${HELM_NAME}" | tee -a "${GITHUB_STEP_SUMMARY}"

          echo "solo-version=${{ vars.ADHOC_XTS_SOLO_VERSION }}" >> "${GITHUB_OUTPUT}"
          echo "helm-release-name=${HELM_NAME}" >> "${GITHUB_OUTPUT}"
          echo "solo-ge-0440=${SOLO_GE_0440}" >> "${GITHUB_OUTPUT}"

  state-validator-uberjar:
    name: Build & Publish Hedera State Validator Uber JAR
    if: ${{ inputs.execute-state-validator-build == true }}
    uses: ./.github/workflows/zxc-build-publish-state-validator.yaml
    with:
      ref: ${{ inputs.ref }}
      dry-run-enabled: "true"

  xts-execution:
    name: Execute XTS
    needs:
      - parameters
    uses: ./.github/workflows/zxc-xts-tests.yaml
    with:
      ref: ${{ inputs.ref }}
      branch_name: ${{ inputs.branch_name }}
      solo-version: ${{ needs.parameters.outputs.solo-version }}
      helm-release-name: ${{ needs.parameters.outputs.helm-release-name }}
      mirror-node-version: ${{ vars.CITR_MIRROR_NODE_VERSION }}
      solo-ge-0440: ${{ needs.parameters.outputs.solo-ge-0440 }}
      enable-timing-sensitive-test-suite: ${{ inputs.enable-timing-sensitive-test-suite }}
      enable-hammer-test-suite: ${{ inputs.enable-hammer-test-suite }}
      enable-hapi-test-suite: ${{ inputs.enable-hapi-test-suite }}
      enable-otter-test-suite: ${{ inputs.enable-otter-test-suite }}
      enable-chaos-otter-test-suite: ${{ inputs.enable-chaos-otter-test-suite }}
      enable-hedera-node-jrs-panel: ${{ inputs.enable-hedera-node-jrs-panel }}
      enable-sdk-tck-regression-panel: ${{ inputs.enable-sdk-tck-regression-panel }}
      enable-mirror-node-regression-panel: ${{ inputs.enable-mirror-node-regression-panel }}
      enable-rpc-relay-regression-panel: ${{ inputs.enable-rpc-relay-regression-panel }}
      enable-block-node-regression-panel: ${{ inputs.enable-block-node-regression-panel }}
      custom-job-label: "XTS (Dry Run):"
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
      platform-access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      regression-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      slack-citr-details-token: ${{ secrets.SLACK_CITR_DETAILED_REPORTS_WEBHOOK }}
      slack-tck-report-webhook: ${{ secrets.SLACK_TCK_MONITOR_WEBHOOK }}

  report-flaky-tests:
    name: Report Flaky Tests
    needs:
      - xts-execution
    if: ${{ !cancelled() && always() }}
    uses: ./.github/workflows/800-call-report-flaky-test.yaml
    with:
      workflow-context: dry-run
    secrets:
      access-token: ${{ secrets.GITHUB_TOKEN }}
