# SPDX-License-Identifier: Apache-2.0
name: "ZXC: TCK Regression"
on:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag, or SHA to checkout:"
        required: false
        type: string
      custom-job-name:
        description: "The custom job name to use for the job:"
        required: false
        type: string
      solo-version:
        description: "The version of solo to install (if not specified, latest will be used):"
        required: false
        type: string
    secrets:
      access-token:
        description: "GitHub Access Token with write permissions to the repository."
        required: true
      slack-tck-report-webhook:
        description: "Slack Webhook URL for TCK Group Monitoring."
        required: true
      slack-detailed-report-webhook:
        description: "Slack Webhook URL for TCK Monitoring."
        required: true

defaults:
  run:
    shell: bash

permissions:
  checks: write
  contents: read
  actions: write
  statuses: write
  id-token: write

env:
  SOLO_CLUSTER_NAME: "solo-tck-e2e"
  SOLO_NAMESPACE: "solo-tck-e2e"
  SOLO_DEPLOYMENT: "solo-tck-deployment"
  SOLO_CLUSTER_SETUP_NAMESPACE: "solo-setup"
  GRADLE_EXEC: ionice -c 2 -n 2 nice -n 19 ./gradlew
  RUN_LOG_NAME: "run.tck-regression.log"

jobs:
  # Execute TCK Regression Tests using specified version of hiero-consensus-node
  tck-regression:
    name: ${{ inputs.custom-job-name || 'Standard' }}
    runs-on: hl-cn-sdk-tck-lin-lg
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      #  Check out the specified hiero-consensus-node reference
      - name: Checkout Consensus Node
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref || '' }}
          fetch-depth: 0

      #  Checkout the sdk-tck repository and the TCK SDK Client
      - name: Checkout Regression Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: platform-sdk/regression
          repository: hiero-ledger/hiero-sdk-tck
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout Latest Tag (TCK)
        run: |
          cd platform-sdk/regression
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest TCK tag: ${LATEST_TAG}"
          git checkout ${LATEST_TAG}

      # Checkout the JS-SDK server
      - name: Checkout JS-SDK Server
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: platform-sdk/sdk-server
          repository: hiero-ledger/hiero-sdk-js
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout Latest Tag (JS-SDK)
        run: |
          cd platform-sdk/sdk-server
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest JS-SDK tag: ${LATEST_TAG}"
          git checkout ${LATEST_TAG}

      # Set up Java Environment
      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 25

      # Set up the node environment
      # Version 20.18.0 is the recommended version for solo.
      - name: Setup NodeJS Environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.18.0

      - name: Setup PNPM
        run: |
          npm install -g pnpm

      # Set up the gradle environment
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        with:
          cache-read-only: false

      # Build the hiero-consensus-node artifacts
      - name: Build hiero-consensus-node
        run: ${GRADLE_EXEC} assemble

      # Set up the npm dependencies and cache on the tck-client
      - name: Set up the tck-client
        run: |
          npm cache clean --force
          npm install
        working-directory: platform-sdk/regression

      # Set up the npm dependencies and cache on the sdk-server
      - name: Install NodeJS Dependencies (sdk-server)
        id: start-sdk-server
        run: |
          # Extract package versions from the parent package.json
          SDK_VERSION=$(node -e "console.log(require('../package.json').version)")
          LONG_VERSION=$(node -e "console.log(require('../package.json').dependencies.long)")
          PROTO_VERSION=$(node -e "console.log(require('../packages/proto/package.json').version)")

          echo "Using SDK version: ${SDK_VERSION}"
          echo "Using long version: ${LONG_VERSION}"
          echo "Using proto version: ${PROTO_VERSION}"

          # Install with the extracted versions
          pnpm add @hiero-ledger/sdk@^${SDK_VERSION} long@${LONG_VERSION} @hiero-ledger/proto@${PROTO_VERSION}
          pnpm install
          nohup pnpm start &
          server_pid=$!
          echo "pid=${server_pid}" >> "${GITHUB_OUTPUT}"
        working-directory: platform-sdk/sdk-server/tck

      # Prepare Hiero Solo
      - name: Prepare Hiero Solo
        id: solo-action
        timeout-minutes: 20
        uses: hiero-ledger/hiero-solo-action@8cda77e13916d1ed8f80eb07361a474a264be005 # latest on `main` currently
        with:
          installMirrorNode: true
          mirrorNodeVersion: v0.138.0
          soloVersion: ${{ inputs.solo-version || 'latest' }}

      # Start the TCK client
      - name: Start tck-client
        env:
          OPERATOR_ACCOUNT_ID: "0.0.2"
          OPERATOR_ACCOUNT_PRIVATE_KEY: "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"
          JSON_RPC_SERVER_URL: "http://127.0.0.1:8544"
          NODE_IP: "127.0.0.1:50211"
          MIRROR_NODE_REST_URL: "http://127.0.0.1:5551"
          MIRROR_NODE_REST_JAVA_URL: "http://127.0.0.1:8084"
          NODE_TIMEOUT: "30000"
          MIRROR_NETWORK: "127.0.0.1:5600"
          NODE_ACCOUNT_ID: "0.0.3"
        run: |
          version=$(solo --version | grep Version | awk '{print $3}')
          if [[ "$(printf '%s\n' "$version" "0.44.0" | sort -V | head -n1)" == "0.44.0" ]]; then
            solo ledger account create --dev --ed25519-private-key "${{ env.OPERATOR_ACCOUNT_PRIVATE_KEY }}" --deployment ${{ steps.solo-action.outputs.deployment }} --hbar-amount 1000000
          else
            solo account create --dev --ed25519-private-key "${{ env.OPERATOR_ACCOUNT_PRIVATE_KEY }}" --deployment ${{ steps.solo-action.outputs.deployment }} --hbar-amount 1000000
          fi
          cp .env.custom_node .env
          npm run test
        working-directory: platform-sdk/regression # required

      - name: SDK TCK Regression Test Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ !cancelled() }}
        with:
          name: SDK TCK Regression Test Report
          path: "**/platform-sdk/regression/mochawesome-report/mochawesome.*"
          retention-days: 7

      # Collect run logs in a log file, ignore last job as it is the one that runs this workflow
      - name: Collect run logs in a log file
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.access-token }}
        run: |
          for job_id in $(gh run view ${{ github.run_id }} --json jobs --jq '.jobs | map(.databaseId) | .[0:-1] | .[]'); do
            echo "Fetching logs for job ${job_id}..."

            current_job_name=$(gh run view ${{ github.run_id }} --json jobs | jq --argjson job_id "${job_id}" -r '.jobs[] | select(.databaseId == $job_id) | .name')

            echo "Logs for job $current_job_name :" >> "${RUN_LOG_NAME}"

            gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/hiero-ledger/hiero-consensus-node/actions/jobs/"${job_id}"/logs >> "${RUN_LOG_NAME}"
          done

      - name: Upload log as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        continue-on-error: true
        with:
          name: SDK TCK Run Logs
          path: ${{ env.RUN_LOG_NAME }}

      # Stop the TCK server
      - name: Stop tck-server
        if: ${{ always() }}
        run: |
          echo ${{ steps.start-sdk-server.outputs.pid }}
          kill -9 ${{ steps.start-sdk-server.outputs.pid }}

  report-tck-regression-status:
    name: ${{ inputs.custom-job-name || 'Standard' }} Slack Report
    runs-on: hl-cn-sdk-tck-lin-sm
    needs:
      - tck-regression
    if: ${{ always() }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Build Slack Payload Message
        id: payload
        run: |
          COLOR="#FF0000"
          if [[ "${{ needs.tck-regression.result }}" == "success" ]]; then
            COLOR="#00FF00"
          elif [[ "${{ needs.tck-regression.result }}" == "cancelled" ]]; then
            COLOR="#555555"
          fi
          cat <<EOF > slack_payload.json
          {
            "attachments": [
              {
                "color": "${COLOR}",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": ":vertical_traffic_light: Hiero Consensus Node - TCK Regression Test Report",
                      "emoji": true
                    }
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*TCK Regression Panel was executed. See status below.*"
                    },
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "TCK Regression Panel Result"
                      },
                      {
                        "type": "plain_text",
                        "text": "${{ needs.tck-regression.result }}"
                      }
                    ]
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Workflow and Commit Information*"
                    },
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Source Commit*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/commit/${{ inputs.ref }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Workflow run ID*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": " ${{ github.run_id }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Workflow run URL*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF

      - name: Report Status to CITR Detailed Test Results
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook: ${{ secrets.slack-detailed-report-webhook }}
          webhook-type: incoming-webhook
          payload-templated: true
          payload-file-path: slack_payload.json
