# SPDX-License-Identifier: Apache-2.0
name: "Delete automation Latitude Namespaces"
permissions:
  contents: read
  id-token: write

on:
  schedule:
    - cron: "0 23 * * *"
    # at 6pm Central Time
  workflow_dispatch:
    inputs:
      Dallas_n1:
        type: boolean
        required: false
        default: false
        description: "*solo-sdpt-n1 (Daily SDPT)"

      Dallas_n2:
        type: boolean
        required: false
        default: false
        description: "*solo-sdlt-n2 (Daily SDLT)"

      Dallas_n3:
        type: boolean
        required: false
        default: false
        description: "*solo-mdlt-n3 (weekly runs)"

      Dallas_n4:
        type: boolean
        required: false
        default: false
        description: "*solo-mdlt-n4 (weekly runs)"

      Chicago_n5:
        type: boolean
        required: false
        default: false
        description: "*solo-<sd*t|mqpt>-n5 (branch testing)"

      Chicago_n6:
        type: boolean
        required: false
        default: false
        description: "*solo-<sd*t|mqpt>-n6 (branch testing)"

      Chicago_n7:
        type: boolean
        required: false
        default: false
        description: "*solo-<sd*t|mqpt>-n7 (branch testing)"

      Chicago_n8:
        type: boolean
        required: false
        default: false
        description: "*solo-<sd*t|mqpt>-n8 (SDPT/SDLT/MQPT)"

      Chicago_n9:
        type: boolean
        required: false
        default: false
        description: "*solo-<sd*t|mqpt>-n9 (SDPT/SDLT/MQPT)"

      Dallas_n10:
        type: boolean
        required: false
        default: false
        description: "*solo-mqpt-n10 (Merge Queues PT/LT)"

      Dallas_n11:
        type: boolean
        required: false
        default: false
        description: "*solo-mqpt-n11 (Merge Queues PT/LT)"

      Dallas_n12:
        type: boolean
        required: false
        default: false
        description: "*solo-mqpt-n12 (Merge Queues PT/LT)"

      Dallas_n13:
        type: boolean
        required: false
        default: false
        description: "*solo-sd*t-n13 (AdHoc Tests: Platform-CI)"

      Chicago_n14:
        type: boolean
        required: false
        default: false
        description: "*solo-sd*t-n14 (AdHoc Tests)"

jobs:
  delete-selected-namespaces:
    runs-on: hl-cn-default-lin-sm
    env:
      Dallas_n1: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.Dallas_n1 }}
      Dallas_n2: ${{ github.event_name == 'schedule' && 'true' || github.event.inputs.Dallas_n2 }}
      Dallas_n3: ${{ github.event.inputs.Dallas_n3 }}
      Dallas_n4: ${{ github.event.inputs.Dallas_n4 }}
      Chicago_n5: ${{ github.event.inputs.Chicago_n5 }}
      Chicago_n6: ${{ github.event.inputs.Chicago_n6 }}
      Chicago_n7: ${{ github.event.inputs.Chicago_n7 }}
      Chicago_n8: ${{ github.event.inputs.Chicago_n8 }}
      Chicago_n9: ${{ github.event.inputs.Chicago_n9 }}
      Dallas_n10: ${{ github.event_inputs.Dallas_n10 }}
      Dallas_n11: ${{ github.event_inputs.Dallas_n11 }}
      Dallas_n12: ${{ github.event_inputs.Dallas_n12 }}
      Dallas_n13: ${{ github.event_inputs.Dallas_n13 }}
      Chicago_n14: ${{ github.event_inputs.Chicago_n14 }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install KubeCtl
        uses: step-security/setup-kubectl@2edbf6aff97d814e9dc52827498ac51fe972e6d0 # v4.0.0

      - name: Install Teleport Client
        uses: teleport-actions/setup@176c25dfcd19cd31a252f275d579822b243e7b9c # v1.0.6
        with:
          version: 18.4.0

      - name: Authorize Teleport SSH Access
        id: auth-ssh
        uses: teleport-actions/auth@685adaf480dc79262a99220eb158a92136d5abd9 # v2.0.3
        with:
          proxy: hashgraph.teleport.sh:443
          token: gh-citr-performance-svcs-bot
          certificate-ttl: 24h

      - name: Authorize Teleport K8S Access to Dallas Cluster
        id: auth-k8s-dal
        uses: teleport-actions/auth-k8s@677da98eaa78a5e649d4c5b4012750af4c28af73 # v2.0.3
        with:
          proxy: hashgraph.teleport.sh:443
          token: gh-citr-performance-svcs-bot
          kubernetes-cluster: k8s.pft.dal.lat.ope.eng.hashgraph.io
          certificate-ttl: 24h

      - name: Get all namespaces in Dallas cluster
        run: sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces

      - name: Dallas Latitude namespaces
        run: |
          set +e
          set +x
          clusterZone="Dallas"
          for namespace in `sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces | awk '{print $1}' | grep -E '(solo)-(sdpt|sdlt|mqpt|mdlt)-n([1-9]|1[0-2])$'`
          do
            n="$(echo "${namespace}" | perl -ne 'print "$1\n" if /(?:solo)-(?:sdpt|sdlt|mqpt|mdlt)-n(\d+)$/')"
            echo "Found {$namespace} with n=${n}"
            env | grep ${clusterZone}_n${n}
            isChecked=$(env | grep ${clusterZone}_n${n} | awk -F= '{print $NF}')
            if [[ "${isChecked}" = "true" ]]
            then
              echo "Deleting ${namespace}"
              sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt delete namespace ${namespace}
            fi
          done
          exit 0

      - name: Authorize Teleport K8S Access to Chicago Cluster
        id: auth-k8s-chi
        uses: teleport-actions/auth-k8s@677da98eaa78a5e649d4c5b4012750af4c28af73 # v2.0.3
        with:
          proxy: hashgraph.teleport.sh:443
          token: gh-citr-performance-svcs-bot
          kubernetes-cluster: k8s.pft.chi.lat.ope.eng.hashgraph.io
          certificate-ttl: 24h

      - name: Get all namespaces in Chicago cluster
        run: sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces

      - name: Chicago Latitude namespaces
        run: |
          set +e
          set +x
          clusterZone="Chicago"
          for namespace in `sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt get namespaces | awk '{print $1}' | grep -E '(solo)-(sdpt|sdlt|mqpt|mdlt)-n([1-9]|1[0-2])$'`
          do
            n="$(echo "${namespace}" | perl -ne 'print "$1\n" if /(?:solo)-(?:sdpt|sdlt|mqpt|mdlt)-n(\d+)$/')"
            echo "Found {$namespace} with n=${n}"
            env | grep ${clusterZone}_n${n}
            isChecked=$(env | grep ${clusterZone}_n${n} | awk -F= '{print $NF}')
            if [[ "${isChecked}" = "true" ]]
            then
              echo "Deleting ${namespace}"
              sh "${{ github.workspace }}"/.github/workflows/support/citr/kubectlt delete namespace ${namespace}
            fi
          done
          exit 0
