# SPDX-License-Identifier: Apache-2.0
name: "ZXF: [CITR] Adhoc - Single Day Longevity Test Controller"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The git ref (branch or tag) to checkout"
        required: false
        default: ""
      test-asset:
        required: true
        default: "AdHocSD8"
        description: "Test on given Longevity Machine (AdHoc5, AdHoc6, AdHoc7, AdHocSD8, AdHocSD9)"
        type: choice
        options:
          - AdHoc5
          - AdHoc6
          - AdHoc7
          - AdHoc13
          - AdHoc14
          - AdHocSD8
          - AdHocSD9
      nlg-accounts: #'-R -c 32 -a 100000000 -T 1000 -n 100000 -S hot -p 50 -tt 1m
        required: true
        default: "100000"
        description: "Number of Accounts and NFT tokens"
        type: choice
        options:
          - "100000"
          - "1000000"
          - "20000000"
          - "100000000"
          - "500000000"
          - "1000000000"
      nlg-time: #'-R -c 32 -a 100000000 -T 1000 -n 100000 -S hot -p 50 -tt 1m
        required: true
        default: "3"
        description: "Test execution time options"
        type: choice
        options:
          - "3"
          - "9"
          - "21"
          - "30"
          - "60"
          - "180"
          - "330"
          - "720"
          - "960"
          - "1200"
          - "10080"
          - "20160"
      add-app-props:
        required: false
        default: ""
        type: string
        description: 'Add props to application.properties, e.g. "blockStream.streamMode=RECORDS". Newline is "\n"'
      add-settings:
        required: false
        default: ""
        type: string
        description: 'Add props to settings.txt, e.g. "state.saveStatePeriod, 300". Newline is "\n"'
      reconnect-uptime:
        required: false
        default: "600"
        type: string
        description: "Reconnect uptime (secs). Downtime is Uptime x 3"
      disable-notifications:
        required: false
        default: true
        type: boolean
        description: "If true, skip tag and notifications"
      delete-namespace:
        required: false
        default: true
        type: boolean
        description: "If true, automatically delete namespace when done"

defaults:
  run:
    shell: bash

permissions:
  contents: write
  id-token: write
  actions: write
  statuses: write

jobs:
  verify-tag:
    name: Verify Tag
    runs-on: hl-cn-sdlt-lin-sm
    continue-on-error: true
    outputs:
      build-number: ${{ steps.verify-tag.outputs.build-number }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Consensus Node
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Verify Tag
        id: verify-tag
        env:
          PROMOTED_GREP_PATTERN: "build-(.{5})" # Pattern to match build tags (e.g., build-12345)
          CHECK_TAG: "${{ inputs.ref || github.ref }}"
        run: |
          # Ensure the tag that we received is a build tag
          # if the tag is a build tag then we can parse out the build number (the last 5 characters)
          # return the build tag as an output
          # if the tag is not a build tag then we will fail the workflow
          if [[ "${CHECK_TAG}" =~ ${PROMOTED_GREP_PATTERN} ]]; then
            echo "The tag is a valid build tag."
            BUILD_NUMBER="${BASH_REMATCH[1]}"
            echo "build-number=${BUILD_NUMBER}" >> "${GITHUB_OUTPUT}"

            echo "### Running SDLT" >> "${GITHUB_STEP_SUMMARY}"
            echo "Build number: ${BUILD_NUMBER}" >> "${GITHUB_STEP_SUMMARY}"
          else
            echo "::notice title=Invalid Build Tag::The provided tag (${CHECK_TAG}) is not a valid build tag."

            echo "### Running SDLT" >> "${GITHUB_STEP_SUMMARY}"
            echo "Ref: ${CHECK_TAG}" >> "${GITHUB_STEP_SUMMARY}"
          fi

  run-single-day-longevity-test:
    name: Longevity Test
    needs:
      - verify-tag
    uses: ./.github/workflows/zxc-single-day-longevity-test.yaml
    if: ${{ needs.verify-tag.result == 'success' || inputs.disable-notifications == true }}
    with:
      test-asset: "${{ inputs.test-asset }}" # TODO: Once Chewie application is installed we can remove this input.
      ref: "${{ inputs.ref || github.ref }}"
      solo-version: "${{ vars.ADHOC_SOLO_VERSION }}"
      nlg-accounts: "${{ inputs.nlg-accounts }}"
      nlg-time: "${{ inputs.nlg-time }}"
      add-app-props: "${{ inputs.add-app-props }}"
      add-settings: "${{ inputs.add-settings }}"
      reconnect-uptime: "${{ inputs.reconnect-uptime }}"
      delete-namespace: ${{ inputs.delete-namespace }}
    secrets:
      slack-report-webhook: ${{ secrets.SLACK_CITR_DETAILED_REPORTS_WEBHOOK }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  tag-sdlt-result:
    name: Tag SDLT Result
    runs-on: hl-cn-sdlt-lin-sm
    needs:
      - run-single-day-longevity-test
      - verify-tag
    if: ${{ inputs.disable-notifications != true }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Consensus Node
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          fetch-depth: "0"
          ref: ${{ inputs.ref || github.ref }}

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v6.1.0
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.SVCS_GPG_KEY_CONTENTS }}
          passphrase: ${{ secrets.SVCS_GPG_KEY_PASSPHRASE }}

      - name: Tag SDLT Result
        run: |
          RESULT="${{ needs.run-single-day-longevity-test.outputs.result }}"
          BUILD_NUM="${{ needs.verify-tag.outputs.build-number }}"

          # Skip tagging if no build number is found
          if [[ -z "${BUILD_NUM}" ]]; then
            echo "No build number found. Skipping tagging step." >> "${GITHUB_STEP_SUMMARY}"
            exit 0
          fi

          # Populate the SDLT tag name and message
          if [[ "${RESULT}" == "success" ]]; then
            TAG_NAME="sdlt-pass-${BUILD_NUM}"
            MSG="Single Day Longevity Test passed for build-${BUILD_NUM}"
          elif [[ "${RESULT}" == "failure" ]]; then
            TAG_NAME="sdlt-fail-${BUILD_NUM}"
            MSG="Single Day Longevity Test FAILED for build-${BUILD_NUM}"
          else
            echo "No tag will be applied. Test result was: ${RESULT}" >> "${GITHUB_STEP_SUMMARY}"
            exit 0
          fi

          git tag --annotate "${TAG_NAME}" --message "${MSG}"
          git push --set-upstream origin --tags

          echo "### SDLT Result - Tag Information" >> "${GITHUB_STEP_SUMMARY}"
          echo "SDLT Tag: ${TAG_NAME}" >> "${GITHUB_STEP_SUMMARY}"

  get-commit-info:
    name: Get Commit Information
    runs-on: hl-cn-sdlt-lin-sm
    if: ${{ inputs.disable-notifications != true }}
    needs:
      - verify-tag
    outputs:
      commit-author: ${{ steps.find-commit-author-slack.outputs.commit-author }}
      commit-email: ${{ steps.find-commit-author-slack.outputs.commit-email }}
      slack-user-id: ${{ steps.find-commit-author-slack.outputs.slack-user-id }}
      commit: ${{ steps.find-commit-author-slack.outputs.commit }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Find Commit Author in Slack
        id: find-commit-author-slack
        continue-on-error: true
        env:
          BUILD_TAG: ${{ inputs.ref || github.ref }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_CITR_BOT_TOKEN }}
        run: |
          # Extract the commit and user information from the build tag
          COMMIT=$(git rev-list -n 1 "${BUILD_TAG}")
          EMAIL=$(git log -1 --pretty=format:'%ae' "${COMMIT}")
          AUTHOR=$(git log -1 --pretty=format:'%an' "${COMMIT}")
          SLACK_USER_ID=$(curl -s -X GET "https://slack.com/api/users.list" \
            -H "Authorization: Bearer ${SLACK_BOT_TOKEN}" | jq -r --arg email "${EMAIL}" \
            '.members[] | select((.profile.email // "" | ascii_downcase) == ($email | ascii_downcase)) | .name')

          if [[ -z "${SLACK_USER_ID}" || "${SLACK_USER_ID}" == "null" ]]; then
            echo "No Slack user found for email: ${EMAIL}"
            SLACK_USER_ID="No matching slack user found"
          else
            echo "Found slack user for email: ${EMAIL}"
            SLACK_USER_ID="<@${SLACK_USER_ID}>"
          fi
          echo "commit=${COMMIT}" >> "${GITHUB_OUTPUT}"
          echo "slack-user-id=${SLACK_USER_ID}" >> "${GITHUB_OUTPUT}"
          echo "commit-author=${AUTHOR}" >> "${GITHUB_OUTPUT}"
          echo "commit-email=${EMAIL}" >> "${GITHUB_OUTPUT}"

  report-success:
    name: Report SDLT execution success
    runs-on: hl-cn-sdlt-lin-sm
    needs:
      - verify-tag
      - tag-sdlt-result
      - run-single-day-longevity-test
      - get-commit-info
    if: ${{ (needs.verify-tag.result == 'success' &&
      needs.tag-sdlt-result.result == 'success' &&
      needs.run-single-day-longevity-test.outputs.result == 'success' &&
      needs.get-commit-info.result == 'success') &&
      inputs.disable-notifications != true && !cancelled() }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Report Success (slack)
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook: ${{ secrets.SLACK_CITR_OPERATIONS_WEBHOOK }}
          webhook-type: incoming-webhook
          payload-templated: true
          payload: |
            {
              "attachments": [
                {
                  "color": "#00FF00",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": ":tada: SDLT - Single Day Longevity Test (${{ inputs.ref || github.ref }}) Passed",
                        "emoji": true
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*SDLT Job Succeeded. Test panel status below*"
                      },
                      "fields": [
                        {
                          "type": "plain_text",
                          "text": "Verify Tag for SDLT"
                        },
                        {
                          "type": "plain_text",
                          "text": "${{ needs.verify-tag.result }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "Run Single Day Longevity Test"
                        },
                        {
                          "type": "plain_text",
                          "text": "${{ needs.run-single-day-longevity-test.outputs.result  }}"
                        },
                        {
                          "type": "plain_text",
                          "text": "Tag SDLT Passing"
                        },
                        {
                          "type": "plain_text",
                          "text": "${{ needs.tag-sdlt-result.result }}"
                        }
                      ]
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Workflow, Tag, and Commit Information*"
                      },
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Source Tag*:"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "<${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.ref || github.ref }}>"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Commit author*:"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "${{ needs.get-commit-info.outputs.commit-author }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow run ID*:"
                        },
                        {
                          "type": "mrkdwn",
                          "text": " ${{ github.run_id }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Workflow run URL*:"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }

  report-failure:
    name: Report SDLT execution failure
    runs-on: hl-cn-sdlt-lin-sm
    needs:
      - verify-tag
      - run-single-day-longevity-test
      - tag-sdlt-result
      - get-commit-info
      - report-success
    if: ${{ (needs.verify-tag.result != 'success' ||
      needs.tag-sdlt-result.result != 'success' ||
      needs.run-single-day-longevity-test.outputs.result != 'success' ||
      needs.get-commit-info.result != 'success' ||
      needs.report-success.result != 'success') &&
      inputs.disable-notifications != true && !cancelled() && always() }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
          ref: ${{ inputs.ref || github.ref }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Collect run logs in a log file
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        continue-on-error: true
        run: |
          for job_id in $(gh run view ${{ github.run_id }} --json jobs --jq '.jobs | map(.databaseId) | .[0:-1] | .[]'); do
            echo "Fetching logs for job $job_id..."

            current_job_name=$(gh run view ${{ github.run_id }} --json jobs | jq --argjson job_id "$job_id" -r '.jobs[] | select(.databaseId == $job_id) | .name')

            echo "Logs for job $current_job_name :" >> run.log

            gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/hiero-ledger/hiero-consensus-node/actions/jobs/$job_id/logs >> run.log
          done

      - name: Upload log as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        continue-on-error: true
        with:
          path: run.log

      - name: Set Create-Alert Flag
        id: set-alert-flag
        run: |
          CREATE_ALERT="false"
          if [[ "${{ needs.verify-tag.result }}" =~ ^(cancelled|failure)$ ]] \
            || [[ "${{ needs.tag-sdlt-result.result }}" =~ ^(cancelled|failure)$ ]] \
            || [[ "${{ needs.get-commit-info.result }}" =~ ^(cancelled|failure)$ ]] \
            || [[ "${{ needs.report-success.result }}" =~ ^(cancelled|failure)$ ]]; then
            CREATE_ALERT="true"
          fi
          echo "create=${CREATE_ALERT}" >> "${GITHUB_OUTPUT}"

      - name: Build Rootly Summary
        id: rootly-summary
        run: |
          summary="The AdHoc SDLT Job Failed"
          echo "summary=${summary}" >> "${GITHUB_OUTPUT}"
          {
            echo 'details<<EOF'
            echo "------------------------------------"
            echo "Status of each job:"
            echo "- Verify Tag: ${{ needs.verify-tag.result }}"
            echo "- Run Single Day Longevity Test: ${{ needs.run-single-day-longevity-test.outputs.result }}"
            echo "- Tag SDLT Result: ${{ needs.tag-sdlt-result.result }}"
            echo "- Get Commit Info: ${{ needs.get-commit-info.result }}"
            echo "- Report Success: ${{ needs.report-success.result }}"
            echo "------------------------------------"
            echo "Commit information:"
            echo "- Commit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ needs.get-commit-info.outputs.commit }}>"
            echo "- Workflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
            echo EOF
          } >> "${GITHUB_OUTPUT}"

      - name: Log Rootly Summary
        run: |
          echo "## Rootly Summary:"
          echo "### Summary: ${{ steps.rootly-summary.outputs.summary }}" >> "${GITHUB_STEP_SUMMARY}"
          echo "${{ steps.rootly-summary.outputs.details }}" >> "${GITHUB_STEP_SUMMARY}"

      - name: Create Rootly Alert
        if: ${{ steps.set-alert-flag.outputs.create == 'true' }}
        uses: pandaswhocode/rootly-alert-action@fdae1529e5aed62040016accf719a0ceb7dae57f # v1.0.0
        continue-on-error: true
        with:
          api_key: ${{ secrets.ROOTLY_API_TOKEN }}
          summary: ${{ steps.rootly-summary.outputs.summary }}
          details: ${{ steps.rootly-summary.outputs.details }}
          notification_target_type: "Service"
          notification_target: "CI/CD Workflows"
          set_as_noise: "false"
          alert_urgency: "Medium"
          environments: "CITR"
          external_id: ${{ github.run_id }}
          external_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Build Slack Payload Message
        id: payload
        run: |
          cat <<EOF > slack_payload.json
          {
            "attachments": [
              {
                "color": "#FF0000",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": ":grey_exclamation: SDLT - Single Day Longevity Test (${{ inputs.ref || github.ref }}) Failed",
                      "emoji": true
                    }
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*SDLT Job Resulted in failure. See status below.*"
                    },
                    "fields": [
                      {
                        "type": "plain_text",
                        "text": "Verify Tag for SDLT"
                      },
                      {
                        "type": "plain_text",
                        "text": "${{ needs.verify-tag.result }}"
                      },
                      {
                        "type": "plain_text",
                        "text": "Run Single Day Longevity Test"
                      },
                      {
                        "type": "plain_text",
                        "text": "${{ needs.run-single-day-longevity-test.outputs.result }}"
                      },
                      {
                        "type": "plain_text",
                        "text": "Tag SDLT Passing"
                      },
                      {
                        "type": "plain_text",
                        "text": "${{ needs.tag-sdlt-result.result }}"
                      },
                      {
                        "type": "plain_text",
                        "text": "Get Commit Information"
                      },
                      {
                        "type": "plain_text",
                        "text": "${{ needs.get-commit-info.result }}"
                      }
                    ]
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Workflow, Tag, and Commit Information*"
                    },
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Source Tag*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ inputs.ref || github.ref }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit author*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "${{ needs.get-commit-info.outputs.commit-author }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Slack user*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "${{ needs.get-commit-info.outputs.slack-user-id }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Workflow run ID*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": " ${{ github.run_id }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Workflow run URL*:"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>"
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF

      - name: Report failure (slack citr-failures)
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook: ${{ secrets.SLACK_CITR_FAILURES_WEBHOOK }}
          webhook-type: incoming-webhook
          payload-templated: true
          payload-file-path: slack_payload.json
